# Generated by Django 5.0.6 on 2024-07-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_order_date_order_timestamp_alter_order_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='street',
            field=models.CharField(max_length=255),
        ),
    ]
